-- RLS policies are intentionally managed in supabase/rls-hardening.sql.
-- Do not recreate broad `using (true) with check (true)` policies here.
-- Keeping this file non-destructive prevents accidental rollback of organization-scoped RLS.
